apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: gitops-imagetag
spec:
  inputs:
    params:
    - name: GIT_USERNAME
      description: The username to be used for the git commit.
      type: string
      default: "manuela-tekton"
    - name: GIT_EMAIL
      description: The email to be used for the git commit.
      type: string
      default: "manuela-team@redhat.com"
    - name: GIT_COMMENT
      description: The comment to be used for the git commit.
      type: string
      default: "Image tag updated by Tekton task gitops-imagetag"
    # - name: TMP_PATCHED_FILE
    #   description: The name of the temporary patch result file. Internal. 
    #   type: string
    #   default: "resource_patched.yaml"
    - name: RESOURCE_PATH
      description: The path of the resource to be patched.
      type: string
      default: "config/instances/manuela-tst/kustomization.yaml"
    # - name: PATCH_COMMAND
    #   description: The patch command to apply to the resource.
    #   type: string
    #   default: '{"images":[{"name":"image-registry.openshift-image-registry.svc:5000/manuela-tst-all/messaging","newTag":"1.1.1"}]}'
    #   #default: '{"spec":{"tags":[{"name":"latest","from":{"name":"iot-consumer:latest"}}]}}'
    - name: YAML_PATH
      description: the yq yaml path of the value to be changed
      type: string
      default: images.(name==line-dashboard).newTag
    resources:
    - name: source
      type: git
    - name: source-semver
      type: git  
  steps:
  - name: patch-imagetag
    image: mikefarah/yq:3.2.1
    script: |
        #!/usr/bin/env sh
        semver=$(cat /workspace/source-semver/components/iot-consumer/VERSION)
        echo $semver
        echo 'Patching $(inputs.params.RESOURCE_PATH)'
        echo ''
        cat $(inputs.params.RESOURCE_PATH)
        echo ''
        yq w -i $(inputs.params.RESOURCE_PATH) '$(inputs.params.YAML_PATH)' $semver
        echo ''
        cat $(inputs.params.RESOURCE_PATH)
    # image: quay.io/openshift/origin-cli:4.3.0
    # script: |
    #     #!/usr/bin/env bash
    #     oc version
    #     echo ''
    #     semver=$(cat /workspace/source-semver/components/iot-consumer/VERSION)
    #     echo $semver
    #     patch='{"images":[{"name":"image-registry.openshift-image-registry.svc:5000/manuela-tst-all/messaging","newTag":"'"${semver}"'"}]}'
    #     echo $patch
    #     echo 'Patching $(inputs.params.RESOURCE_PATH)'
    #     echo ''
    #     cat $(inputs.params.RESOURCE_PATH)
    #     echo ''
    #     echo 'Patch command is "'$patch'" '
    #     oc patch --type merge --local=true --output='yaml' --patch=$patch --filename=$(inputs.params.RESOURCE_PATH) > $(inputs.params.TMP_PATCHED_FILE)
    #     echo ''
    #     echo 'Output written to $(inputs.params.TMP_PATCHED_FILE)'
    #     echo ''
    #     cat $(inputs.params.TMP_PATCHED_FILE)
    #     echo ''
    #     echo 'Replacing $(inputs.params.RESOURCE_PATH) with $(inputs.params.TMP_PATCHED_FILE)'
    #     mv $(inputs.params.TMP_PATCHED_FILE) $(inputs.params.RESOURCE_PATH)
    workingdir: /workspace/source
  - name: git-push
    image: alpine/git
    env:
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: github
            key: token
      - name: GITHUB_USER
        valueFrom:
          secretKeyRef:
            name: github
            key: user      
    script: |
        #!/usr/bin/env sh
        echo "https://$GITHUB_USER:$GITHUB_TOKEN@github.com" > ~/.git-credentials
        git config --global credential.helper store 'store --file ~/.git-credentials'
        git version
        git config --global user.email "$(inputs.params.GIT_EMAIL)"
        git config --global user.name "$(inputs.params.GIT_USERNAME)"
        echo ''
        echo 'Adding $(inputs.params.RESOURCE_PATH) to git index'
        git add $(inputs.params.RESOURCE_PATH)
        git commit -m '$(inputs.params.GIT_COMMENT)'
        git push --set-upstream origin master
    workingdir: /workspace/source