kind: Task
apiVersion: tekton.dev/v1alpha1
metadata:
  name: mock
spec:
  inputs:
    params:
      - name: MESSAGE
        description: |
          The message to echo.
        default: "Hello from mock-task"
  steps:
  - image: node  # contains node
    script: |
      #!/usr/bin/env node
      console.log("$(inputs.params.MESSAGE)")