kind: Task
apiVersion: tekton.dev/v1alpha1
metadata:
  name: skopeo-copy
spec:
  inputs:
    resources:
    - name: remote-image
      type: image 
    - name: local-image
      type: image
  steps:
  - name: skopeo-copy
    image: quay.io/redhat-emea-ssa-team/skopeo-ubi:latest
    command:
      - skopeo
    args:
      - "copy"
      - "--authfile=/pushsecret/.dockerconfigjson"
      - "--src-tls-verify=false"
      - "docker://$(inputs.resources.local-image.url)"
      - "docker://$(inputs.resources.remote-image.url)"