apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    application: iot-software-sensor
    template: openjdk18-web-basic-s2i
    app.kubernetes.io/part-of: ManuELA
  name: iot-software-sensor
  annotations:
    app.openshift.io/connects-to: broker-amq-mqtt-ss
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentConfig: iot-software-sensor
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        application: iot-software-sensor
        deploymentConfig: iot-software-sensor
      name: iot-software-sensor
    spec:
      containers:
        - env:
            - name: COMPONENT_MQTT_HOSTNAME
              value: broker-amq-mqtt-all-0-svc
            - name: COMPONENT_MQTT_PORT
              value: "61616"
            - name: mqtt.username
              value: iotuser
            - name: mqtt.password
              value: iotuser
          image: iot-software-sensor:latest
          imagePullPolicy: Always
          name: iot-software-sensor
          ports:
            - containerPort: 8778
              name: jolokia
              protocol: TCP
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8443
              name: https
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 75
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - iot-software-sensor
        from:
          kind: ImageStreamTag
          name: 'iot-software-sensor:latest'
      type: ImageChange
    - type: ConfigChange