apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- operator.yaml
- role_binding.yaml
- role.yaml
- service_account.yaml
- crds/manuela.redhat.com_networkpaths_crd.yaml
- crds/manuela.redhat.com_v1alpha1_networkpath_cr.yaml