apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

bases:
- ../manuela-team-rolebindings

resources:
- argocd-namespace.yaml
- argocd-operatorgroup.yaml
- argocd-subscription.yaml