apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: iot-consumer-pipeline-run-1
spec:
  pipelineRef:
    name: iot-consumer-pipeline
  resources:
  - name: gitops-repo
    resourceRef:
      name: manuela-gitops
  - name: remote-image
    resourceRef:
      name: quay-consumer-image
  - name: git-repo
    resourceRef:
      name: manuela-git
  - name: local-image
    resourceRef:
      name: ocp-consumer-image    