apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- odh-instance.yaml
- seldon-deployment-crd.yaml
- ito-anomaly-detection-bc.yaml  
- ito-anomaly-detection-route.yaml   
- ito-anomaly-detection-is.yaml  
- ito-anomaly-detection-seldon.yaml
