apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- iotdemo-namespace.yaml
- iotdemo-rolebinding.yaml
- iotdemo-operatorgroup.yaml
#- iotdemo-secrets.yaml
bases:
- iot-consumer/manifests
- iot-frontend/manifests
- iot-software-sensor/manifests
namespace: iotdemo
