apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iotdemo

resources:
- iotdemo-rolebinding.yaml

bases:
- iot-consumer/manifests
- iot-frontend/manifests
- iot-software-sensor/manifests
- iot-software-sensor-quarkus/manifests

# Open data hub is optional
# - iot-anomaly-detection/manifests

#the following causes an error if the rolebindings admin and view have already been created
#- ../namespaces_and_operator_subscriptions/iotdemo


