apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- iotdemo-rolebinding.yaml

bases:
- iot-consumer/manifests
- iot-frontend/manifests
- iot-software-sensor/manifests
- ../namespaces_and_operator_subscriptions/iotdemo

namespace: iotdemo
