resources:
- iotdemo-namespace.yaml
- iotdemo-rolebinding.yaml
- iotdemo-operatorgroup.yaml
bases:
- iot-consumer/manifests
- iot-frontend/manifests
- iot-software-sensor/manifests
namespace: iotdemo

