apiVersion: v1
kind: BuildConfig
metadata:
  name: edge-anomaly-detection
  annotations:
    description: >
      Source-to-Image (S2I) builder image for serving an anomaly detection model
  labels:
    component: serving
spec:
  output:
    to:
      kind: ImageStreamTag
      name: edge-anomaly-detection:0.2.0
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/sa-mw-dach/manuela-dev.git
    type: Git
    contextDir: "components/edge-anomaly-detection"
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi7/python-36
    type: Source
  triggers:
    - type: ConfigChange

