apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- nodeshift-is.yaml
- iot-frontend-bc.yaml
- iot-frontend-dc.yaml
- iot-frontend-is.yaml
- iot-frontend-route.yaml
- iot-frontend-svc.yaml

configMapGenerator:
- name: iot-frontend-cfg
  files:
  - config.json=iot-frontend-configmap-config.json