apiVersion: v1
kind: Service
metadata:
  labels:
    seldon-app: anomaly-detection-predictor
  name: anomaly-detection-metrics
spec:
  ports:
  - name: metrics
    port: 6000
    protocol: TCP
    targetPort: 6000
  selector:
    seldon-app: anomaly-detection-predictor
  sessionAffinity: None
  type: ClusterIP