apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: s2i
spec:
  workspaces:
  - name: gitrepos
    description: The git repo will be cloned onto the volume backing this workspace
  params:
  - name: BUILDER_IMAGE
    description: The location of the s2i builder image.
    type: string
  - name: PATH_CONTEXT
    default: .
    description: The location of the path to run s2i from.
    type: string
  - name: TLSVERIFY
    default: "true"
    description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS registry)
    type: string
  - name: LOGLEVEL
    default: "0"
    description: Log level when running the S2I binary
    type: string
  - name: subdirectory
    default: "dev"
    description: subdirectory in the gitrepos workspace where the dev repo has been cloned to
    type: string
  - name: OUTPUT_IMAGE
    type: string
  - name: TAG
    default: latest 
    type: string
  steps:
  - name: generate
    image: quay.io/openshift-pipeline/s2i
    command:
    - s2i
    - build
    - --loglevel=$(params.LOGLEVEL)
    - $(params.PATH_CONTEXT)
    - $(params.BUILDER_IMAGE)
    - --as-dockerfile
    - /gen-source/Dockerfile.gen
    resources: {}
    volumeMounts:
    - mountPath: /gen-source
      name: gen-source
    workingDir: /workspace/gitrepos/$(params.subdirectory)
  - name: build
    image: quay.io/buildah/stable:v1.11.0
    script: |
      buildah bud --tls-verify=$(params.TLSVERIFY) --layers -f /gen-source/Dockerfile.gen -t $(params.OUTPUT_IMAGE) .
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/lib/containers
      name: varlibcontainers
    - mountPath: /gen-source
      name: gen-source
    workingDir: /gen-source
  - name: push
    image: quay.io/buildah/stable:v1.11.0
    script: |
      buildah push --tls-verify=$(params.TLSVERIFY) $(params.OUTPUT_IMAGE) docker://$(params.OUTPUT_IMAGE):$(params.TAG)
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/lib/containers
      name: varlibcontainers
  volumes:
  - emptyDir: {}
    name: varlibcontainers
  - emptyDir: {}
    name: gen-source