apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: networkpaths.manuela.redhat.com
spec:
  group: manuela.redhat.com
  names:
    kind: NetworkPath
    listKind: NetworkPathList
    plural: networkpaths
    singular: networkpath
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
