kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: nodejs:latest
  SourceLocation: ./
  SourceType: local
  Ports:
  - 8080/TCP
  Application: manu
  Project: dev
  Name: consumer
  Envs:
  - Name: VIBRATION_ANOMALY_ENABLED
    Value: "true"
  - Name: VIBRATION_ALERT_ENABLED
    Value: "true"
  - Name: ANOMALY_DETECTION_URL
    Value: https://anomaly-detection-iotdemo.apps-crc.testing
  - Name: NODE_TLS_REJECT_UNAUTHORIZED
    Value: "0"
