kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:image-pullers
  namespace: iotdemo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated