apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iotdemo

bases:
  - ../../components/iot-consumer/manifests
  - ../../components/iot-frontend/manifests
  - ../../components/iot-software-sensor/manifests