kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: modern-webapp:latest
  SourceLocation: ./
  SourceType: local
  Ports:
  - 8080/TCP
  Application: test-app
  Project: sbergste-ui-test
  Name: manu-front
  Url:
  - Name: manu
    Port: 8080
