apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: anomaly-detection-model
  namespace: model-dev
spec:
  name: anomaly-ml
  predictors:
  - graph:
      implementation: SKLEARN_SERVER
      modelUri:  s3://manuela-ml
      envSecretRefName: seldon-init-container-secret
      name: classifier
    name: default
    replicas: 1

