apiVersion: v1
kind: Secret
metadata:
  name: seldon-init-container-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: cmjJ8LbFD5wi0Jf9Jo68
  AWS_SECRET_ACCESS_KEY: GPRzLereAIUeaZq9mCaRbyVWw01c8F1crkAo3xFR
  AWS_ENDPOINT_URL: s3-openshift-storage.apps.ocp4.stormshift.coe.muc.redhat.com
  USE_SSL: false
