apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: firewallrules.manuela.redhat.com
spec:
  group: manuela.redhat.com
  names:
    kind: FirewallRule
    listKind: FirewallRuleList
    plural: firewallrules
    singular: firewallrule
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
