apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: iot-software-sensor-quarkus
  name: iot-software-sensor-quarkus
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: iot-software-sensor-quarkus:latest
  postCommit: {}
  resources: 
    limits:
      cpu: '4'
      memory: 4Gi
  runPolicy: Serial
  source:
    git:
      ref: camel-quarkus-sensor
      uri: https://github.com/sa-mw-dach/manuela-dev.git
    type: Git
    contextDir: "components/iot-software-sensor-quarkus"
  strategy:
    sourceStrategy:
      forcePull: true
      from:
        kind: ImageStreamTag
        name: 'ubi-quarkus-native-s2i:19.3.1-java11'
    type: Source     
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - type: ImageChange
status: 
  lastVersion: 0